name: main

# 毎日00:00(UST)に実行
on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  actions: write
  checks: write
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Python
        run: python src/main.py
      - name: Commit files
        run: |
          git add -N . # 新規ファイルを含める
          if ! git diff --exit-code --quiet
          then
            git config --local user.name "thistle"
            git config --local user.email "thistle0420@gmail.com"
            git add .
            git commit -m "Update Json" -a
            git push origin master
          fi